FROM python:3.9.1-buster

# Set up environment
ENV PYTHONUNBUFFERED 1
RUN apt-get update && apt-get install -y gettext
RUN apt-get install -y nginx

# Set up logs directory
RUN mkdir /logs
RUN touch /logs/access.log
RUN touch /logs/gunicorn.log

# Set up requirements directory
RUN mkdir /requirements
ADD ./requirements /requirements/

# Set up code directory
RUN mkdir /code
WORKDIR /code
ADD ./api /code/
COPY ./docker/entrypoints/entrypoint.sh /entrypoint.sh

# Set up nginx
COPY ./docker/docker_nginx/django_nginx.conf /etc/nginx/sites-available/django_nginx.conf
RUN rm /etc/nginx/sites-enabled/default

# Set up requirements
RUN pip install -r /requirements/remote.txt

#read
VOLUME ["/logs"]

# Port to expose
EXPOSE 80
