# Generated by Django 3.1.5 on 2021-02-06 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('priority', models.IntegerField()),
                ('images_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSectionItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naturitas_id', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('image_file_name', models.CharField(max_length=100)),
                ('link_path', models.URLField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.homesection')),
            ],
        ),
        migrations.AddField(
            model_name='homesection',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='home.homesectiontype'),
        ),
    ]
