# Generated by Django 3.1.5 on 2021-02-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='deeplink_path',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
